// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAnIm29kd6-Vrin6j5RQ91s2oenZ68sjM',
    appId: '1:46357465108:web:26df9be8c2e91075977f01',
    messagingSenderId: '46357465108',
    projectId: 'doctor-a0382',
    authDomain: 'doctor-a0382.firebaseapp.com',
    storageBucket: 'doctor-a0382.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClIBROv7_8NpWuPYTOzH8_w9TJ_vBya_4',
    appId: '1:46357465108:android:b1b35fe1e096267c977f01',
    messagingSenderId: '46357465108',
    projectId: 'doctor-a0382',
    storageBucket: 'doctor-a0382.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-Y70jnZ7YqZfqbRz92AHb7f-zOSY_e_I',
    appId: '1:46357465108:ios:5aeef579a0ff965b977f01',
    messagingSenderId: '46357465108',
    projectId: 'doctor-a0382',
    storageBucket: 'doctor-a0382.appspot.com',
    iosClientId: '46357465108-06dnuqe05kec8nhjfnc0s1i45arkgol2.apps.googleusercontent.com',
    iosBundleId: 'com.example.doctor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-Y70jnZ7YqZfqbRz92AHb7f-zOSY_e_I',
    appId: '1:46357465108:ios:5aeef579a0ff965b977f01',
    messagingSenderId: '46357465108',
    projectId: 'doctor-a0382',
    storageBucket: 'doctor-a0382.appspot.com',
    iosClientId: '46357465108-06dnuqe05kec8nhjfnc0s1i45arkgol2.apps.googleusercontent.com',
    iosBundleId: 'com.example.doctor',
  );
}
